import Link from "next/link";
import { CheckCircle2, ShieldAlert, ExternalLink } from "lucide-react";

// Public — no auth, no DashboardLayout. Anyone with the URL from a PDF
// can hit this page and confirm the report came from Lime++.
export const dynamic = "force-dynamic";

type VerifyResponse = {
  id: string;
  type: "individual" | "project";
  generatedAt: string;
  dataHash: string;
  project: {
    id: string;
    name: string;
    repository: string | null;
    organization: string;
    department: string;
  };
  subject: { name: string | null; githubUsername: string | null } | null;
  generatedBy: { name: string | null; githubUsername: string | null };
  summary: Record<string, unknown>;
};

async function fetchVerification(id: string): Promise<VerifyResponse | null> {
  try {
    const res = await fetch(
      `${process.env.NEXT_PUBLIC_API_URL}/reports/verify/${encodeURIComponent(id)}`,
      { cache: "no-store" },
    );
    if (res.status === 404) return null;
    if (!res.ok) return null;
    return (await res.json()) as VerifyResponse;
  } catch {
    return null;
  }
}

function formatDateTime(iso: string) {
  try {
    return new Date(iso).toISOString().replace("T", " ").slice(0, 16) + " UTC";
  } catch {
    return iso;
  }
}

function describePerson(
  person: { name: string | null; githubUsername: string | null } | null,
) {
  if (!person) return "—";
  const parts = [person.name, person.githubUsername && `@${person.githubUsername}`]
    .filter(Boolean)
    .join(" · ");
  return parts || "—";
}

export default async function VerifyReportPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const data = await fetchVerification(id);

  if (!data) {
    return (
      <main className="mx-auto flex min-h-screen max-w-2xl flex-col justify-center px-6 py-10">
        <div className="rounded-2xl border border-destructive/30 bg-destructive/5 p-8">
          <div className="flex items-center gap-3">
            <ShieldAlert className="h-7 w-7 text-destructive" />
            <h1 className="text-2xl font-bold">Report not recognized</h1>
          </div>
          <p className="mt-3 text-muted-foreground">
            No Lime++ report matches the verification ID
            <code className="mx-1 rounded bg-muted px-1.5 py-0.5 font-mono text-xs">
              {id}
            </code>
            .
          </p>
          <p className="mt-2 text-sm text-muted-foreground">
            If you received a PDF that points here, it was not generated by
            Lime++, or the record has been deleted. Treat the document as
            unverified.
          </p>
          <Link
            href="/"
            className="mt-6 inline-block text-sm font-medium text-primary hover:underline"
          >
            Go to Lime++
          </Link>
        </div>
      </main>
    );
  }

  return (
    <main className="mx-auto max-w-3xl px-6 py-10">
      <header className="mb-8 flex items-center justify-between">
        <div>
          <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
            Lime++ · Report verification
          </p>
          <h1 className="mt-1 text-2xl font-bold">Authenticity confirmed</h1>
        </div>
        <CheckCircle2 className="h-10 w-10 text-emerald-500" />
      </header>

      <section className="rounded-2xl border border-emerald-500/30 bg-emerald-500/5 p-6">
        <p className="text-sm leading-relaxed">
          This report was generated by Lime++ on{" "}
          <strong>{formatDateTime(data.generatedAt)}</strong>. The numbers
          printed on the PDF match the snapshot Lime++ stored at that moment.
        </p>
      </section>

      <section className="mt-6 grid gap-3 rounded-2xl border border-border bg-card p-6">
        <Row label="Report type">
          {data.type === "individual"
            ? "Individual contribution report"
            : "Project evaluation report"}
        </Row>
        <Row label="Project">{data.project.name}</Row>
        <Row label="Organization">{data.project.organization}</Row>
        <Row label="Department">{data.project.department}</Row>
        {data.project.repository && (
          <Row label="Repository">
            <a
              href={`https://github.com/${data.project.repository}`}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1 text-primary hover:underline"
            >
              {data.project.repository}
              <ExternalLink className="h-3 w-3" />
            </a>
          </Row>
        )}
        {data.subject && (
          <Row label="Subject">{describePerson(data.subject)}</Row>
        )}
        <Row label="Generated by">{describePerson(data.generatedBy)}</Row>
        <Row label="Generated at">{formatDateTime(data.generatedAt)}</Row>
      </section>

      <section className="mt-6 rounded-2xl border border-border bg-card p-6">
        <h2 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">
          Snapshot summary
        </h2>
        <dl className="mt-3 grid grid-cols-2 gap-3 text-sm sm:grid-cols-3">
          {Object.entries(data.summary).map(([key, value]) => (
            <div key={key} className="rounded-lg bg-muted/40 p-3">
              <dt className="text-xs uppercase tracking-wider text-muted-foreground">
                {key.replace(/([A-Z])/g, " $1").trim()}
              </dt>
              <dd className="mt-1 text-base font-semibold">{String(value)}</dd>
            </div>
          ))}
        </dl>
      </section>

      <section className="mt-6 rounded-2xl border border-border bg-card p-6">
        <h2 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">
          Cryptographic fingerprint
        </h2>
        <p className="mt-2 text-xs text-muted-foreground">
          The PDF was hashed with SHA-256 over its canonical payload at
          generation time. If the printed numbers were altered after download,
          a recipient who recomputes the hash will get a different value than
          the one stored here.
        </p>
        <code className="mt-3 block break-all rounded-md bg-muted p-3 font-mono text-[11px]">
          {data.dataHash}
        </code>
        <p className="mt-3 text-xs text-muted-foreground">
          Report ID:{" "}
          <span className="font-mono text-foreground">{data.id}</span>
        </p>
      </section>

      <footer className="mt-10 text-center text-xs text-muted-foreground">
        Lime++ · Objective Technical Evaluation ·{" "}
        <Link href="/" className="text-primary hover:underline">
          Visit Lime++
        </Link>
      </footer>
    </main>
  );
}

function Row({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <div className="grid grid-cols-3 gap-3 text-sm">
      <dt className="text-muted-foreground">{label}</dt>
      <dd className="col-span-2 font-medium">{children}</dd>
    </div>
  );
}
